spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/adabook?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format-sql: true
jwt:
  secret: secret

api:
  security:
    token:
      secret: ${JWT_SECRET:adabook123456}